version: '3.7'
services:
  pg:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=hoplin1234!"
      - "POSTGRES_DB=template"
      - "TZ=Asia/Seoul"
    ports:
      - "5432:5432"
    networks:
      - mogakoffee
networks:
  mogakoffee:
      driver: bridge